/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author dforeman
 */
public class CreateAdminAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAdminAccount
     */
    public CreateAdminAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdminName = new javax.swing.JTextField();
        lblEnterAdminName = new javax.swing.JLabel();
        lblCreateNewAdminAccount = new javax.swing.JLabel();
        txtAdminAddress = new javax.swing.JTextField();
        lblEnterAdminAddress = new javax.swing.JLabel();
        lblEnterAdminID = new javax.swing.JLabel();
        txtAdminID = new javax.swing.JTextField();
        txtAdminPassword = new javax.swing.JTextField();
        lblEnterAdminPassword = new javax.swing.JLabel();
        btnEnterAdminAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminNameActionPerformed(evt);
            }
        });

        lblEnterAdminName.setText("Enter Admin Name");

        lblCreateNewAdminAccount.setText("Create New Admin Account");

        txtAdminAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminAddressActionPerformed(evt);
            }
        });

        lblEnterAdminAddress.setText("Enter Admin Address");

        lblEnterAdminID.setText("Enter Admin ID");

        txtAdminID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminIDActionPerformed(evt);
            }
        });

        txtAdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminPasswordActionPerformed(evt);
            }
        });

        lblEnterAdminPassword.setText("Enter Admin Password");

        btnEnterAdminAccount.setText("Enter Admin Account");
        btnEnterAdminAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterAdminAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAdminName)
                                .addComponent(lblEnterAdminName)
                                .addComponent(lblCreateNewAdminAccount)
                                .addComponent(txtAdminAddress)
                                .addComponent(lblEnterAdminAddress)
                                .addComponent(lblEnterAdminID)
                                .addComponent(txtAdminID)
                                .addComponent(txtAdminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addComponent(lblEnterAdminPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnEnterAdminAccount)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblCreateNewAdminAccount)
                .addGap(18, 18, 18)
                .addComponent(lblEnterAdminID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterAdminPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnterAdminName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnterAdminAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnterAdminAccount)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdminIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminIDActionPerformed

    private void txtAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminPasswordActionPerformed

    private void txtAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminNameActionPerformed

    private void txtAdminAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAddressActionPerformed

    private void btnEnterAdminAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterAdminAccountActionPerformed
        // TODO add your handling code here:
        
        ProcessAccount();
    }//GEN-LAST:event_btnEnterAdminAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAdminAccount().setVisible(true);
            }
        });
    }
    
    public void ProcessAccount()
    {               
        String newAdminID = txtAdminID.getText();
        String newAdminPassword = txtAdminPassword.getText();
        String newAdminName = txtAdminName.getText();
        String newAdminAddress = txtAdminAddress.getText();
        
        //check for valid ID
        if((newAdminID.contains("a")) && (newAdminID.contains("%%%%")))
        {
            
            Classes.SystemUser newAccount = new Classes.SystemUser(newAdminID, newAdminPassword, newAdminName, newAdminAddress);
        
            FileFunctions.AddAccount addNewAccount = new FileFunctions.AddAccount();
        
            addNewAccount.AddAccount(newAccount);
        }
        //notify user of invalid ID
        else
        {
          System.out.println("bruh");  
        }
        //enter information into SystemUser Object
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterAdminAccount;
    private javax.swing.JLabel lblCreateNewAdminAccount;
    private javax.swing.JLabel lblEnterAdminAddress;
    private javax.swing.JLabel lblEnterAdminID;
    private javax.swing.JLabel lblEnterAdminName;
    private javax.swing.JLabel lblEnterAdminPassword;
    private javax.swing.JTextField txtAdminAddress;
    private javax.swing.JTextField txtAdminID;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPassword;
    // End of variables declaration//GEN-END:variables
}
